const express=require('express');const http=require('http');const cors=require('cors');const fs=require('fs');const path=require('path');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const {Server}=require('socket.io');
const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'CHANGE_ME_MCLAND_SECRET';const DATA=path.join(__dirname,'data');fs.mkdirSync(DATA,{recursive:true});const files={users:path.join(DATA,'users.json'),friends:path.join(DATA,'friends.json'),messages:path.join(DATA,'messages.json')};for(const f of Object.values(files))if(!fs.existsSync(f))fs.writeFileSync(f,'[]');const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));const write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2));
const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:'*'}});app.use(cors());app.use(express.json({limit:'2mb'}));app.get('/api/health',(_,r)=>r.json({ok:true,service:'MC LAND'}));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'ورود لازم است'});req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({error:'توکن نامعتبر است'})}}
app.post('/api/auth/register',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');if(!/^[A-Za-z0-9_\u0600-\u06FF -]{3,16}$/.test(username)||password.length<6)return res.status(400).json({error:'اطلاعات نامعتبر است'});const users=read(files.users);if(users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'نام کاربری تکراری است'});const u={id:Date.now().toString(36),username,passwordHash:await bcrypt.hash(password,10),avatar:'',createdAt:new Date().toISOString()};users.push(u);write(files.users,users);const token=jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:'30d'});res.json({token,user:{id:u.id,username:u.username,avatar:''}})});
app.post('/api/auth/login',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');const u=read(files.users).find(x=>x.username.toLowerCase()===username.toLowerCase());if(!u||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({error:'نام کاربری یا رمز عبور اشتباه است'});res.json({token:jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:'30d'}),user:{id:u.id,username:u.username,avatar:u.avatar||''}})});
app.get('/api/me',auth,(req,res)=>{const u=read(files.users).find(x=>x.id===req.user.id);res.json({user:u?{id:u.id,username:u.username,avatar:u.avatar||'',createdAt:u.createdAt}:null})});
app.put('/api/me/avatar',auth,(req,res)=>{const avatar=String(req.body.avatar||'');if(avatar.length>1500000)return res.status(413).json({error:'عکس بزرگ است'});const users=read(files.users),u=users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'کاربر پیدا نشد'});u.avatar=avatar;write(files.users,users);res.json({ok:true,avatar})});
app.post('/api/friends',auth,(req,res)=>{const target=String(req.body.username||'').trim(),users=read(files.users),other=users.find(u=>u.username.toLowerCase()===target.toLowerCase());if(!other||other.id===req.user.id)return res.status(404).json({error:'دوست پیدا نشد'});const fs=read(files.friends);if(!fs.some(x=>(x.a===req.user.id&&x.b===other.id)||(x.a===other.id&&x.b===req.user.id))){fs.push({a:req.user.id,b:other.id});write(files.friends,fs)}res.json({ok:true})});
app.get('/api/friends',auth,(req,res)=>{const users=read(files.users),ids=read(files.friends).filter(x=>x.a===req.user.id||x.b===req.user.id).map(x=>x.a===req.user.id?x.b:x.a);res.json({friends:users.filter(u=>ids.includes(u.id)).map(u=>({id:u.id,username:u.username,avatar:u.avatar||''}))})});
app.get('/api/leaderboard',(_,res)=>{res.json({players:read(files.users).slice(0,10).map((u,i)=>({rank:i+1,username:u.username,avatar:u.avatar||'',score:0}))})});
app.get('/api/messages/:friendId',auth,(req,res)=>{const key=[req.user.id,req.params.friendId].sort().join(':');res.json({messages:read(files.messages).filter(m=>m.key===key).slice(-100)})});
io.use((socket,next)=>{try{socket.user=jwt.verify(socket.handshake.auth?.token||'',SECRET);next()}catch{next(new Error('unauthorized'))}});io.on('connection',socket=>{socket.on('chat:send',p=>{const to=String(p?.to||''),text=String(p?.text||'').trim().slice(0,500);if(!to||!text)return;const msg={key:[socket.user.id,to].sort().join(':'),from:socket.user.id,fromUsername:socket.user.username,to,text,createdAt:new Date().toISOString()};const all=read(files.messages);all.push(msg);write(files.messages,all.slice(-5000));io.to(socket.user.id).to(to).emit('chat:message',msg)})});
server.listen(PORT,()=>console.log('MC LAND backend running on '+PORT));